---
# https://pep8speaks.com/

scanner:
    diff_only: True
    linter: 'pycodestyle'

pycodestyle:
    max-line-length: 100
    ignore:
        - W503 # line break before binary operator
        - W504 # line break after binary operator
        - E402 # module level import not at top of file
        - E731 # do not assign a lambda expression, use a def
        - C406 # unnecessary list literal - rewrite as a dict literal
        - E741 # ambiguous variable name
    exclude: []
    count: False
    first: False
    show-pep8: False
    show-source: False
    statistics: False
    hang-closing: False
    filename: []
    select: []

no_blank_comment: True
descending_issues_order: False
only_mention_files_with_errors: True

message:
    opened:
        header: 'Hello @{name}! Thanks for opening this PR.'
        footer: ''
    updated:
        header: ''
        footer: ''
    no_errors: 'There are currently no PEP 8 issues detected in this PR.'
